# Generated by Django 5.1.7 on 2025-03-29 22:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yureka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedvideo',
            name='approved_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='curatedvideo',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yureka.video'),
        ),
        migrations.AlterField(
            model_name='socialauth',
            name='provider',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='socialauth',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yureka.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userroutine',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yureka.topic'),
        ),
        migrations.AlterField(
            model_name='userroutine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yureka.user'),
        ),
        migrations.AlterField(
            model_name='usertopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yureka.topic'),
        ),
        migrations.AlterField(
            model_name='usertopic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yureka.user'),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='videotopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yureka.topic'),
        ),
        migrations.AlterField(
            model_name='videotopic',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yureka.curatedvideo'),
        ),
        migrations.CreateModel(
            name='VideoMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('watched_duration', models.IntegerField()),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('session_start', models.DateTimeField()),
                ('session_end', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yureka.user')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yureka.curatedvideo')),
            ],
        ),
        migrations.DeleteModel(
            name='VideoMetric',
        ),
    ]
